### ISSUE TITLE
Arabic traineddata causes segfault

### ISSUE THREAD

**Issue by MuadDev** [tesseract-shadow/tesseract-ocr-re#1]
Using `ara.traineddate` for version 4.0 of tessaract, obtained [here](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files), causes the following error when running `test.sh`:

```
====== TASK TASK_12802_394560981 started ======
mgr->GetComponent(TESSDATA_INTTEMP, &fp):Error:Assert failed:in file adaptmatch.cpp, line 537
/bin/bash: line 1:    81 Segmentation fault      (core dumped) tesseract ../myfile.jpg myfile -l ara --psm 1 --oem 2 txt pdf hocr
====== Result files was copied to ./ocr-files/output/TASK_12802_394560981/ ======
```

What is the cause of this error?
And how can I resolve this?

**Comment by kinjelom** [comment]
Please try now https://github.com/tesseract-shadow/tesseract-ocr-re/commit/1e706edc8c7922af1f5a00c688b555a92b3c09c2

`tesseract-ocr-all` package is required to add all languages support: https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr/+packages

Use https://hub.docker.com/r/tesseractshadow/tesseract4re/ for tests

**Comment by MuadDev** [comment]
Now if I do a fresh git pull of this repo and a docker pull of the container the standard test don't even work anymore, according to this error:
```
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS               NAMES
d8147c84ba03        tesseractshadow/tesseract4re   "/bin/bash"         7 minutes ago       Up 7 minutes                            t4re
====== TASK TASK_8315_303448234 started ======
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
====== Result files was copied to ./ocr-files/output/TASK_8315_303448234/ ======
```
Although more language files (including ara.traineddata & eng.traineddata) have been installed in the docker at path `/usr/share/tesseract-ocr/4.00/tessdata/`

Moreover, tesseract seems to know that there is an english file though:
```
root@d8147c84ba03:/home/work# tesseract --list-langs | grep eng
eng
Bengali
```

**Comment by MuadDev** [comment]
I have found a workaround, which also might be an indication for the problem. Setting the option `--oem` to either `1` ("Neural nets LSTM engine only") or `3` ("Default, based on what is available") seems to resolve the issue for both `eng` and `ara`.

So change `test.sh` like this:
```
...
docker exec -it t4re /bin/bash -c "mkdir -p ./$TASK_TMP_DIR/out/; cd ./$TASK_TMP_DIR/out/; tesseract ../phototest.tif phototest -l eng --psm 1 --oem 3 txt pdf hocr"
...
```
Or this (for my specific case):
```
...
docker exec -it t4re /bin/bash -c "mkdir -p ./$TASK_TMP_DIR/out/; cd ./$TASK_TMP_DIR/out/; tesseract ../phototest.tif phototest -l ara --psm 1 --oem 3 txt pdf hocr"
...
```

**Comment by kinjelom** [comment]
thanks @MuadDev 
done: https://hub.docker.com/r/tesseractshadow/tesseract4re/builds/
